


pido al usuario numero

pido al usuario otro numero

try:

    resultado = numero / otro numero

except:

    print("Error, no podemos resolver...")
